# name_prension: start22
# hf_repo: flamma77/lewm-base
# hf_subdir: tdv
# ablations:
  # - a: 0.0
  #   lr: 5.0e-05
  #   lam: 0.4
  #   pod_id: xpe517jmfd30wt
  #   output_model_name: start2_a0.0_l0.4_lr5e-5
  # - a: 0.0
  #   lr: 5.0e-05
  #   lam: 0.25
  #   pod_id: jyf0gq70b8fdls
  #   output_model_name: start22_a0.0_l0.25_lr5e-5
  

name_prension: start2
hf_repo: flamma77/lewm-base
hf_subdir: tdv_start
eval_output_dir: data
eval_output_hf: false
ablations:
  - a: 0.0
    lr: 5.0e-05
    lam: 0.03
    output_model_name: start2_a0.0_l0.03_lr5e-5
  - a: 0.0
    lr: 5.0e-05
    lam: 0.4
    output_model_name: start2_a0.0_l0.4_lr5e-5
  - a: 0.0
    lr: 5.0e-05
    lam: 1.0
    output_model_name: start2_a0.0_l1.0_lr5e-5
  - a: 1.0
    lr: 5.0e-05
    lam: 0.03
    output_model_name: start2_a1.0_l0.03_lr5e-5